### ISSUE TITLE
Shared Containers

### ISSUE THREAD

**Issue by RSalo** [sonata-project/SonataPageBundle#1395]
Hi. There is a parameter "shared" in containers. It seems to do nothing or I can't fully understand how it should work. Example:
```
containers:
 header:
  name: Header
  shared: true
```
Any example of usage? Thanks!
