### ISSUE TITLE
Entity is not recognised for new projects

### ISSUE THREAD

**Issue by eerison** [sonata-project/SonataPageBundle#1632]
I setup sonata page bundle 4.0 from scratch, But for some reason doctrine doesn't recognized the entities

for example

```php
<?php

declare(strict_types=1);

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Sonata\PageBundle\Entity\BasePage;

#[ORM\Entity]
#[ORM\Table(name: "page__page")]
class SonataPagePage extends BasePage
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    protected $id;
}

```

commands to check the diff

- `bin/console doctrine:migrations:up-to-date`
- `bin/console doctrine:schema:update --dump-sql`

output

```
[OK] Nothing to update - your database is already in sync with the current entity metadata. 
```

```
[OK] Up-to-date! No migrations to execute. 
```

Database
<img width="437" alt="Screenshot 2022-10-24 at 12 34 11" src="https://user-images.githubusercontent.com/6358755/197507058-ba0bdb63-46aa-45a3-877a-eb0e8abf643d.png">

error when I open the page

```
Unable to find the mapping information for the class App\Entity\SonataPageSite. Please check the `auto_mapping` option (http://symfony.com/doc/current/reference/configuration/doctrine.html#configuration-overview) or add the bundle to the `mappings` section in the doctrine configuration.
```

**Comment by eerison** [comment]
I tried to add this mapping
https://symfony.com/doc/current/reference/configuration/doctrine.html#configuration-overview

```
doctrine:
    orm:
        auto_mapping: true
        mappings:
            SonataPageBundle:
                type: xml
                dir: 'Resources/config/doctrine'
```

But I'm getting the same issue
