### ISSUE TITLE
[Doc][Bug] It's throwing an exception when we are decorating PageAdmin

### ISSUE THREAD

**Issue by eerison** [sonata-project/SonataPageBundle#1639]
in version 4.x was removed those parameters

https://github.com/sonata-project/SonataPageBundle/blob/3.x/src/Resources/config/admin.xml#L7-L25

I didn't test it yet, But I suspect the only way to overwrite the classes like `PageAdmin` is decorating right?

I don't know! I'll do some tests and add some doc/UPGRADE notes for this!

**Comment by eerison** [comment]
In this case if I want to overwrite the `PageAdmin` I need to do like this right?

```php
<?php

namespace App\Admin;

use Knp\Menu\ItemInterface;
use Sonata\AdminBundle\Admin\AbstractAdmin;
use Sonata\AdminBundle\Admin\AdminInterface;
use Sonata\AdminBundle\Datagrid\DatagridMapper;
use Sonata\AdminBundle\Datagrid\ListMapper;
use Sonata\AdminBundle\Form\FormMapper;
use Sonata\AdminBundle\Route\RouteCollectionInterface;
use Sonata\AdminBundle\Show\ShowMapper;

class PageAdmin extends AbstractAdmin
{
    private AdminInterface $admin;

    public function __construct(AbstractAdmin $admin)
    {
        parent::__construct();

        $this->admin = $admin;
    }

    protected function configureRoutes(RouteCollectionInterface $collection): void
    {
        $this->admin->configureRoutes($collection);
    }

    protected function preUpdate(object $object): void
    {
        $this->admin->preUpdate($object);
    }

    protected function prePersist(object $object): void
    {
        $this->admin->prePersist($object);
    }

    protected function getAccessMapping(): array
    {
        return $this->admin->getAccessMapping();
    }

    protected function configureBatchActions(array $actions): array
    {
        return $this->admin->configureBatchActions($actions);
    }

    protected function alterNewInstance(object $object): void
    {
        $this->admin->alterNewInstance($object);
    }

    protected function configurePersistentParameters(): array
    {
        return $this->admin->configurePersistentParameters();
    }

    protected function configureShowFields(ShowMapper $show): void
    {
        $this->admin->configureShowFields($show);
    }

    protected function configureListFields(ListMapper $list): void
    {
        $this->admin->configureListFields($list);
    }

    protected function configureDatagridFilters(DatagridMapper $filter): void
    {
        $this->admin->configureDatagridFilters($filter);
    }

    protected function configureFormFields(FormMapper $form): void
    {
        $this->admin->configureFormFields($form);
    }

    protected function configureTabMenu(ItemInterface $menu, string $action, ?AdminInterface $childAdmin = null): void
    {
        $this->admin->configureTabMenu($menu, $action, $childAdmin);
    }
}
```

```yaml
App\Admin\PageAdmin:
        decorates: sonata.page.admin.page
        arguments: [ '@App\Admin\PageAdmin.inner' ]
        tags:
            - {name: 'sonata.admin', model_class: 'App\Entity\SonataPagePage', controller: 'sonata.page.controller.admin.page', manager_type: 'orm', group: 'sonata_page', translation_domain: 'SonataPageBundle', label: 'page', label_translator_strategy: 'sonata.admin.label.strategy.underscore', icon: 'fa fa-sitemap' }
```
