### ISSUE TITLE
Web profiler not working after runtime added

### ISSUE THREAD

**Issue by haivala** [sonata-project/SonataPageBundle#1738]
as requested in #1727 

    your composer.json extra config (and what appear when you run composer dump-autoload)
    index.php file
    sonata_page.yaml config

```
  "extra": {
    "symfony-assets-install": "copy",
    "runtime": {
      "class": "Sonata\\PageBundle\\Runtime\\SonataPagePathRuntime"
    },
    "symfony": {
      "allow-contrib": true
    }
  }
```
index.php
```
<?php

use App\Kernel;

require_once dirname(__DIR__).'/vendor/autoload_runtime.php';

return function (array $context) {
    return new Kernel($context['APP_ENV'], (bool) $context['APP_DEBUG']);
};
```
sonata_page
```
sonata_page:
  multisite: host_with_path_by_locale
  use_streamed_response: true
  hide_disabled_blocks: true
  page_defaults:
    decorate: true
  skip_redirection: true
  router_auto_register:
    enabled: true
    priority: 200
  ignore_route_patterns:
    - ^(.*)admin(.*) # ignore admin route, ie route containing 'admin'
    - ^_(.*) # ignore symfony routes
  ignore_routes:
    - sonata_page_esi_cache
    - sonata_page_ssi_cache
    - sonata_page_js_sync_cache
    - sonata_page_js_async_cache
    - sonata_cache_apc
    - sonata_cache_esi
...
  ignore_uri_patterns:
    - ^/admin\/
    - ^/api\/
    - ^/stripe\/

  default_template: default
  templates:
    onecolumn:
...
  direct_publication: "%kernel.debug%"
```

```
# composer.phar dump-autoload                                                              
Generating autoload files
Generated autoload files
```
