### ISSUE TITLE
API returns empty object when controller action returns Pager instance

### ISSUE THREAD

**Issue by borNfreee** [sonata-project/SonataPageBundle#510]
Example: method `/api/page/pages` returns instance of Pager class, but serializer returns empty object `{}`.

Did I miss something in configuration? I only see that DataGridBundle should be installed. Should I configure JMS serializer additionally? 
Please advice.

**Comment by borNfreee** [comment]
Must be configured in such way:

```yml
# app/config/config.yml
jms_serializer:
    metadata:
        directories:
            - { path: %kernel.root_dir%/../vendor/sonata-project/datagrid-bundle/Resources/config/serializer, namespace_prefix: 'Sonata\DatagridBundle' }
```

Created PR to update documentation as it not obvious.
