### ISSUE TITLE
multisite redirects are missing site.relativePath

### ISSUE THREAD

**Issue by thms** [sonata-project/SonataPageBundle#620]
Configure two sites, relative path /one and /two
Configure nginx to handle both and use fcgi to proxy to php.
Configure app_dev.php to use $request = RequestFactory::createFromGlobals('host_with_path');

Force a redirect, either via impersonating a user, or by redirecting in a authentication success listener. Either f these will create a RedirectResponse that uses SiteRequest#getUri(). 
The problem is that getUri() builds the URI without the site's relative path, so the redirects are invalid.
I have tried a few ways to fix this, but always run into issues with inheritance (so I can't inherit and access private members), or hardcoded includes.

Config (as it is relevant to the discussion):

``` yaml
sonata_page:
    class:
#        page: AppBundle\Entity\Page
#        site: AppBundle\Entity\Site
#        block: AppBundle\Entity\Block
#        snapshot: AppBundle\Entity\Snapshot
    direct_publication: %kernel.debug%
    multisite: host_with_path
    use_streamed_response: true # set the value to false in debug mode or if the reverse proxy does not handle streamed response
    # Decide which routes to exclude from handling via the th CMS
    ignore_route_patterns:
        - ^(.*)admin(.*)   # ignore admin route, ie route containing 'admin'
        - ^_(.*)          # ignore symfony debugger routes

    ignore_routes:
        - sonata_page_cache_esi
        - sonata_page_cache_ssi
        - sonata_page_js_sync_cache
        - sonata_page_js_async_cache
        - sonata_cache_esi
        - sonata_cache_ssi
        - sonata_cache_js_async
        - sonata_cache_js_sync
        - sonata_cache_apc

    ignore_uri_patterns:
        - ^/admin\/   # ignore admin route, ie route containing 'admin'

    page_defaults:
        homepage: {decorate: false, enabled: false} # disable decoration for homepage, key - is a page route
```
