### ISSUE TITLE
Generate internal Pages

### ISSUE THREAD

**Issue by hug963** [sonata-project/SonataPageBundle#683]
There is no way that I am aware of to generate internal pages outside of fixtures.

It would be useful to be able to generate them easily, given that the default template is dependent on a ‘global’ internal page.

There could be a setting in the config:

```yaml
sonata_page:
    internal_pages:
        global: Global Page    # renders route_name “_page_internal_global” and name “Global Page"
        blog: Blog Internal Page 
```

It could be done by creating an array with the error pages and the other internal pages in 
https://github.com/sonata-project/SonataPageBundle/blob/3.x/Route/RoutePageGenerator.php#L159
