### ISSUE TITLE
InactiveScopeException while updating core routes

### ISSUE THREAD

**Issue by pulse00** [sonata-project/SonataPageBundle#70]
After updating the sonata bundles to the latest versions (dev-master), i'm getting the following exception when running the update-core-routes command:

```
[Symfony\Component\DependencyInjection\Exception\InactiveScopeException]
 You cannot create a service ("request") of an inactive scope ("request").
```

The exception is gone when i remove the _sonata_admin route from my routing.yml:

``` yaml
_sonata_admin: 
    resource: .
    type: sonata_admin
    prefix: /admin

```

Any idea which changes could have introduced this regression?
