### ISSUE TITLE
Question about overriding and Route handling

### ISSUE THREAD

**Issue by jayesbe** [sonata-project/SonataPageBundle#743]
I am trying to override page routes.  At the moment I am trying to create a homepage for when no Site exists.

This is kind of a base-case. Brand new installation, no Site objects currently exist.

I have created an indexAction inside a DefaultController. The route is "default_homepage"

I currently have my cmf_routing config set as such

```yaml
cmf_routing:
    chain:
        routers_by_id:
            router.default: 100
            sonata.page.router: 50 
```

I also tried

```yaml
cmf_routing:
    chain:
        routers_by_id:
            router.default: 100
            sonata.page.router: 50 
        replace_symfony_router: false
```

I am expecting that when there is no Site defined it would default to the static route "default_homepage"

In the logs I see the following:

[2016-11-28 12:34:54] request.INFO: Matched route "default_homepage". {"route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::indexAction","_route":"default_homepage"},"request_uri":"https://my.example.host.org/app_dev.php/"} []

Which shows it matches the route.. but it results in an internal_error being thrown because there is no Site found.. which sends the response to a 404 result page. 

I also noted that I can remove the cmf_routing configuration all together and there is no change in behaviour.  I also changed priority values on the chained routers to no affect. 

Looking at the core, I see the RequestListener and ResponseListener objects are throwing the errors that send the response to a 404 result.  This sounds sort of like a chicken and egg situation.. I want static pages to load if they are defined if no dynamic pages are defined.  

Since there is no Homepage (since there is no Site), I want the default Homepage to load (static route) .. this doesnt seem possible at the moment... is there another way ?
