### ISSUE TITLE
Allow merging routing ignore_* configuration instead of override it

### ISSUE THREAD

**Issue by gremo** [sonata-project/SonataPageBundle#776]
This bundle provide default values for `ignore_*` routing configuration and this is good.

However if I only need to add something i need to copy/paste the patterns from the configuration, even if defaults are quite good.

I.e. if I need to add a single route to the defaults I can't do the following:

```yml
ignore_routes_merging: true # new option
ignore_routes:
    - sonata_user_profile_show
```

What about merging the configuration with the default values? For BC we can add an option `ignore_routes_merging: false`. This bundle could provide sensible defaults and one can stay up to date with that.
