### ISSUE TITLE
Exception when enabling varnish/esi cache for 'sonata.page.block.container': "Please define a controller key"

### ISSUE THREAD

**Issue by hal869** [sonata-project/SonataPageBundle#977]
I'm setting up Symfony4 + Sonata Block&Page with a Varnish6/ESI cache.

With
```
framework.yaml
	framework:
	    esi: { enabled: true }

sonata_cache:
    caches:
        esi:
            servers:
                - varnishadm -T 127.0.0.1:6082 {{ COMMAND }} "{{ EXPRESSION }}"
```

If I enable
```
sonata_block.yaml
	sonata_block:
	    blocks:
	        sonata.page.block.container:
	            cache: sonata.cache.esi
```

On nav to site frontpage,
```
[2/2] Twig_Error_Runtime

	Twig_Error_Runtime:
	An exception has been thrown during the rendering of a template ("Please define a controller key").
...
```
